/*
*  Copyright 2026 Google LLC
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      https://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

package com.google.cloud.pso.extract;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.cloud.pso.generator.EventGenerator;
import com.google.cloud.pso.model.Event;
import java.util.List;
import org.apache.beam.sdk.transforms.Create;
import org.apache.beam.sdk.transforms.DoFn;
import org.apache.beam.sdk.transforms.PTransform;
import org.apache.beam.sdk.transforms.ParDo;
import org.apache.beam.sdk.values.PBegin;
import org.apache.beam.sdk.values.PCollection;
import org.joda.time.Instant;

/** A PTransform that generates a specified number of events internally using EventGenerator. */
public class CreateEvents extends PTransform<PBegin, PCollection<String>> {

    private final int numEvents;
    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    private CreateEvents(int numEvents) {
        this.numEvents = numEvents;
    }

    public static CreateEvents of(int numEvents) {
        return new CreateEvents(numEvents);
    }

    @Override
    public PCollection<String> expand(PBegin input) {
        // Each session generated by EventGenerator has exactly 30 events.
        // We calculate the number of sessions needed to reach numEvents.
        int numSessions = (int) Math.ceil(numEvents / 30.0);

        List<Event> events =
                EventGenerator.generateMultipleSessions(numSessions, System.currentTimeMillis());

        // Trim the list to match numEvents exactly if needed
        if (events.size() > numEvents) {
            events = events.subList(0, numEvents);
        }

        return input.apply("CreateEvents", Create.of(events))
                .apply(
                        "AssignTimestampsAndSerialize",
                        ParDo.of(
                                new DoFn<Event, String>() {
                                    @ProcessElement
                                    public void processElement(
                                            @Element Event event, OutputReceiver<String> receiver)
                                            throws Exception {
                                        String json = OBJECT_MAPPER.writeValueAsString(event);
                                        receiver.outputWithTimestamp(
                                                json, Instant.ofEpochMilli(event.getTimestamp()));
                                    }
                                }));
    }
}
